// Generated by https://quicktype.io

export interface SearchResponse {
  data:       Gif[];
  pagination: Pagination;
  meta:       Meta;
}

export interface Gif {
  type:                       Type;
  id:                         string;
  url:                        string;
  slug:                       string;
  bitly_gif_url:              string;
  bitly_url:                  string;
  embed_url:                  string;
  username:                   Username;
  source:                     string;
  title:                      string;
  rating:                     Rating;
  content_url:                string;
  source_tld:                 SourceTLD;
  source_post_url:            string;
  is_sticker:                 number;
  import_datetime:            string;
  trending_datetime:          string;
  images:                     Images;
  user?:                      User;
  analytics_response_payload: string;
  analytics:                  Analytics;
}

export interface Analytics {
  onload:  Onclick;
  onclick: Onclick;
  onsent:  Onclick;
}

export interface Onclick {
  url: string;
}

export interface Images {
  original:                 { [key: string]: string };
  downsized:                ImagesProps;
  downsized_large:          ImagesProps;
  downsized_medium:         ImagesProps;
  downsized_small:          DownsizedSmall;
  downsized_still:          ImagesProps;
  fixed_height:             { [key: string]: string };
  fixed_height_downsampled: { [key: string]: string };
  fixed_height_small:       { [key: string]: string };
  fixed_height_small_still: ImagesProps;
  fixed_height_still:       ImagesProps;
  fixed_width:              { [key: string]: string };
  fixed_width_downsampled:  { [key: string]: string };
  fixed_width_small:        { [key: string]: string };
  fixed_width_small_still:  ImagesProps;
  fixed_width_still:        ImagesProps;
  looping:                  { [key: string]: string };
  original_still:           ImagesProps;
  original_mp4:             DownsizedSmall;
  preview:                  DownsizedSmall;
  preview_gif:              ImagesProps;
  preview_webp:             ImagesProps;
  hd?:                      DownsizedSmall;
  "480w_still":             ImagesProps;
}

export interface ImagesProps {
  height: string;
  width:  string;
  size:   string;
  url:    string;
}

export interface DownsizedSmall {
  height:   string;
  width:    string;
  mp4_size: string;
  mp4:      string;
}

export enum Rating {
  G = "g",
  PG = "pg",
}

export enum SourceTLD {
  Empty = "",
  ImgurCOM = "imgur.com",
  The90S90S90SCOM = "90s90s90s.com",
  WWWHalolzCOM = "www.halolz.com",
  WWWRedditCOM = "www.reddit.com",
  WWWYoutubeCOM = "www.youtube.com",
}

export enum Type {
  GIF = "gif",
}

export interface User {
  avatar_url:    string;
  banner_image:  string;
  banner_url:    string;
  profile_url:   string;
  username:      Username;
  display_name:  DisplayName;
  description:   string;
  instagram_url: string;
  website_url:   string;
  is_verified:   boolean;
}

export enum DisplayName {
  DanBahiaDan = "dan.bahia.dan",
  GIPHYGaming = "GIPHY Gaming",
  GavinAvid = "Gavin Avid",
  Regal = "Regal",
  The1Jps = "1jps",
}

export enum Username {
  DanBahiaDan = "dan_bahia_dan",
  Empty = "",
  Gaming = "gaming",
  Gavinreed = "gavinreed",
  Regalmovies = "regalmovies",
  The1Jps = "1jps",
}

export interface Meta {
  status:      number;
  msg:         string;
  response_id: string;
}

export interface Pagination {
  total_count: number;
  count:       number;
  offset:      number;
}
