// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
  numberOfOrders:       number;
  paidOrders:           number;
  numberOfClients:      number;
  numberOfProducts:     number;
  outOfStockProducts:   number;
  lowInventoryProducts: number;
  notPaidOrders:        number;
}
