name: CI-Main

on:
  push:
    branches: ["main"]
  # pull_request:
  #   types: [opened, synchronize]

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: mongodb+srv://github-admin-user:UW3AX3p2WVAi1shO@turborepo.pzvcrtj.mongodb.net/shopdb?retryWrites=true&w=majority
      JWT_SECRET_SEED: Th1s1sAs3cr3tS33d0fMyT0k3n5
      NEXT_PUBLIC_TAX_RATE: 0.15

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      # - name: Test
      #  run: yarn test
