name: CI-Preview

on:
  push:
    branches: ["preview"]
  # pull_request:
  #   types: [opened, synchronize]

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: mongodb+srv://vercel-admin-user:8ad0bc1COkrxzgez@brocodecluster.eo9sf5v.mongodb.net/shop?retryWrites=true&w=majority
      NEXT_PUBLIC_TAX_RATE: 0.15

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      # - name: Test
      #  run: yarn test
